import type { Metadata } from 'next'
import TanstackProvider from '@/Hooks/providers/TanstackProvider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,params }: {children: React.ReactNode, params : {locate: string}}) {

  return (
    <html lang={params.locate}>
      <body>
        <TanstackProvider>
          {children}
        </TanstackProvider>
      </body>
    </html>
  )
}