import type { Metadata } from 'next'
import pick from 'lodash.pick';
import TanstackProvider from '@/Hooks/providers/TanstackProvider'
import {NextIntlClientProvider, useMessages} from "next-intl";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,params }: {children: React.ReactNode, params : {locate: string}}) {
  const messages = useMessages();

  return (
    <html lang={params.locate}>
      <body>
        <TanstackProvider>
        <NextIntlClientProvider
          locale={params.locate}
          messages={pick(messages, 'page')}
        >
          {children}
        </NextIntlClientProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}